language: php

branches:
  # Only test the master branch and SemVer tags.
  only:
    - master
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

matrix:
  include:
    - php: 7.3
      env: dependencies=highest
    - php: 7.2
    - php: 7.1
      env: dependencies=lowest

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  # Do highest/lowest testing by installing dependencies per the 'dependencies' setting
  - if [ -z "$dependencies" ]; then composer install --prefer-dist; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-dist --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update --prefer-dist -n; fi;

script:
  - composer -n test

after_success:
  - travis_retry php vendor/bin/coveralls -v
